<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>B Frequentist Equivalence Testing | Statistics and Research Design</title>
<meta name="author" content="James Bartlett">
<meta name="description" content="In the lectures, we mentioned equivalence testing is another option for statistically supporting there is no meaningful effect present. No technique can support the null hypothesis is precisely 0,...">
<meta name="generator" content="bookdown 0.26 with bs4_book()">
<meta property="og:title" content="B Frequentist Equivalence Testing | Statistics and Research Design">
<meta property="og:type" content="book">
<meta property="og:url" content="https://psyteachr.github.io/statsresdesign/Frequentist-Equivalence.html">
<meta property="og:image" content="https://psyteachr.github.io/statsresdesign/images/logos/logo.png">
<meta property="og:description" content="In the lectures, we mentioned equivalence testing is another option for statistically supporting there is no meaningful effect present. No technique can support the null hypothesis is precisely 0,...">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="B Frequentist Equivalence Testing | Statistics and Research Design">
<meta name="twitter:description" content="In the lectures, we mentioned equivalence testing is another option for statistically supporting there is no meaningful effect present. No technique can support the null hypothesis is precisely 0,...">
<meta name="twitter:image" content="https://psyteachr.github.io/statsresdesign/images/logos/logo.png">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><script src="libs/bs3compat-0.4.1/transition.js"></script><script src="libs/bs3compat-0.4.1/tabs.js"></script><script src="libs/bs3compat-0.4.1/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><script src="libs/kePrint-0.0.1/kePrint.js"></script><link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<!-- Global site tag (gtag.js) - Google Analytics --><script async src="https://www.googletagmanager.com/gtag/js?id=G-6NP3MF25W3"></script><script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-6NP3MF25W3');
    </script><script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- CSS --><style type="text/css">
    
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  </style>
<style type="text/css">
    /* Used with Pandoc 2.11+ new --citeproc when CSL is used */
    div.csl-bib-body { }
    div.csl-entry {
      clear: both;
        }
    .hanging div.csl-entry {
      margin-left:2em;
      text-indent:-2em;
    }
    div.csl-left-margin {
      min-width:2em;
      float:left;
    }
    div.csl-right-inline {
      margin-left:2em;
      padding-left:1em;
    }
    div.csl-indent {
      margin-left: 2em;
    }
  </style>
<link rel="stylesheet" href="include/psyteachr.css">
<link rel="stylesheet" href="include/webex.css">
<link rel="stylesheet" href="include/style.css">
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="">Statistics and Research Design</a>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html">Overview</a></li>
<li><a class="" href="introduction-to-linear-regression-1.html"><span class="header-section-number">1</span> Introduction to Linear Regression 1</a></li>
<li><a class="" href="introduction-to-linear-regression-2.html"><span class="header-section-number">2</span> Introduction to Linear Regression 2</a></li>
<li><a class="" href="introduction-to-generalised-linear-models-1.html"><span class="header-section-number">3</span> Introduction to Generalised Linear Models 1</a></li>
<li><a class="" href="introduction-to-generalised-linear-models-2.html"><span class="header-section-number">4</span> Introduction to Generalised Linear Models 2</a></li>
<li><a class="" href="introduction-to-linear-mixed-effects-models.html"><span class="header-section-number">5</span> Introduction to Linear Mixed Effects Models</a></li>
<li><a class="" href="introduction-to-percentile-bootstrap.html"><span class="header-section-number">6</span> Introduction to Percentile Bootstrap</a></li>
<li><a class="" href="graphical-representations.html"><span class="header-section-number">7</span> Graphical Representations</a></li>
<li><a class="" href="myths-and-fallacies.html"><span class="header-section-number">8</span> Myths and Fallacies</a></li>
<li><a class="" href="introduction-to-bayesian-hypothesis-testing.html"><span class="header-section-number">9</span> Introduction to Bayesian Hypothesis Testing</a></li>
<li><a class="" href="introduction-to-bayesian-estimation.html"><span class="header-section-number">10</span> Introduction to Bayesian Estimation</a></li>
<li class="book-part">Appendices</li>
<li><a class="" href="installing-r.html"><span class="header-section-number">A</span> Installing R</a></li>
<li><a class="active" href="Frequentist-Equivalence.html"><span class="header-section-number">B</span> Frequentist Equivalence Testing</a></li>
<li><a class="" href="conventions.html"><span class="header-section-number">C</span> Conventions</a></li>
<li><a class="" href="glossary-1.html"><span class="header-section-number">D</span> Glossary</a></li>
<li><a class="" href="license.html">License</a></li>
<li><a class="" href="references.html">References</a></li>
</ul>

        <div class="book-extra">
          <p><a id="book-repo" href="https://github.com/psyteachr/statsresdesign">View book source <i class="fab fa-github"></i></a></p>
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="Frequentist-Equivalence" class="section level1" number="12">
<h1>
<span class="header-section-number">B</span> Frequentist Equivalence Testing<a class="anchor" aria-label="anchor" href="#Frequentist-Equivalence"><i class="fas fa-link"></i></a>
</h1>
<p>In the lectures, we mentioned equivalence testing is another option for statistically supporting there is no meaningful effect present. No technique can support the null hypothesis is precisely 0, so equivalence testing flips the standard hypothesis testing logic around.</p>
<p>Instead of testing against a single point-null hypothesis of 0, you can apply two one-sided tests to boundaries representing your smallest effect size of interest. You apply a one-sided test to a lower bound and see whether your effect is significantly higher. You apply a one-sided test to an upper bound and see whether your effect is significantly lower. If both tests are significant, you can conclude your effect is statistically equivalent, at least within your chosen boundaries.</p>
<p>You can apply this technique to different focal tests such as t-tests, correlations, and meta-analyses. The package we will use is called <code class="package">TOSTER</code>. Make sure you install it before running any of the following code, and load the necessary packages for this appendix.</p>
<div class="sourceCode" id="cb139"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Applying equivalence testing in R </span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://aaroncaldwell.us/TOSTERpkg/">TOSTER</a></span><span class="op">)</span>
<span class="co"># Wrangling and plotting functions</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span></code></pre></div>
<p>To follow along to this appendix and try the code yourself, please download the data files we will be using in <a href="data/equivalence_testing.zip">this zip file</a>.</p>
<div id="t-tests" class="section level2" number="12.1">
<h2>
<span class="header-section-number">B.1</span> t-tests<a class="anchor" aria-label="anchor" href="#t-tests"><i class="fas fa-link"></i></a>
</h2>
<p>For a t-test applied to two groups, we will reanalyse data from <span class="citation">Bastian et al. (<a href="references.html#ref-bastian_pain_2014" role="doc-biblioref">2014</a>)</span>. This study wanted to investigate whether experiencing pain together can increase levels of bonding between participants. The study was trying to explain how people often say friendships are strengthened by adversity.</p>
<p>Participants were randomly allocated into two conditions: pain or control. Participants in the pain group experienced mild pain through a cold pressor task (leaving your hand in ice cold water) and a wall squat (sitting against a wall). The control group completed a different task that did not involve pain. The participants then completed a scale to measure how bonded they felt to other participants in the group. Higher values on this scale mean greater bonding.</p>
<p>The independent variable is called <code><span class="st">"CONDITION"</span></code>. The control group has the value 0 and the pain group has the value 1. They wanted to find out whether participants in the pain group would have higher levels of bonding with their fellow participants than participants in the control group. After a little processing, the dependent variable is called <code><span class="st">"mean_bonding"</span></code> for the mean of 7 items related to bonding.</p>
<div class="sourceCode" id="cb140"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">Bastian_data</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="st">"data/Bastian.csv"</span><span class="op">)</span>

<span class="co"># Relabel condition to be more intuitive which group is which </span>
<span class="va">Bastian_data</span><span class="op">$</span><span class="va">CONDITION</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">Bastian_data</span><span class="op">$</span><span class="va">CONDITION</span>, 
                                   levels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fl">1</span><span class="op">)</span>, 
                                   labels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Control"</span>, <span class="st">"Pain"</span><span class="op">)</span><span class="op">)</span>

<span class="co"># We also need to get our DV from the mean of 7 items</span>
<span class="va">Bastian_data</span> <span class="op">&lt;-</span> <span class="va">Bastian_data</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://tidyr.tidyverse.org/reference/pivot_longer.html">pivot_longer</a></span><span class="op">(</span>names_to <span class="op">=</span> <span class="st">"item"</span>, <span class="co"># var for item names</span>
               values_to <span class="op">=</span> <span class="st">"score"</span>, <span class="co"># var for item scores</span>
               cols <span class="op">=</span> <span class="va">group101</span><span class="op">:</span><span class="va">group107</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="co"># Range of columns for group bonding items</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/across.html">across</a></span><span class="op">(</span>.cols <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="op">-</span><span class="va">item</span>, <span class="op">-</span><span class="va">score</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="co"># Group by everything but ignore item and score</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a></span><span class="op">(</span>mean_bonding <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">score</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="co"># Summarise by creating a subscale name and specify sum or mean</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">ungroup</a></span><span class="op">(</span><span class="op">)</span> <span class="co"># Always ungroup</span></code></pre></div>
<p>For t-tests, the package has shifted to a single function that can be applied in different ways:</p>
<ul>
<li><p>For a one-sample t-test, you must enter the mean, SD, and sample size for the sample, alongside the value of mu to test against.</p></li>
<li><p>For an independent samples t-test, you must enter the mean, SD, and sample size for each group.</p></li>
<li><p>For a paired samples t-test, you must enter the mean and SD for each condition, the sample size, and the correlation between conditions.</p></li>
</ul>
<p>Bastian et al. requires the independent samples t-test inputs. The first step will be calculating the summary statistics for our two groups and saving them to clearly label and enter into the TOSTER function later. You could enter the values directly into the function, but I like to calculate them first and save them as objects to avoid copy-paste errors.</p>
<div class="sourceCode" id="cb141"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Group by condition to get one row for control and pain values</span>
<span class="va">Brandt_summary</span> <span class="op">&lt;-</span> <span class="va">Bastian_data</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">CONDITION</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a></span><span class="op">(</span>mean <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">mean_bonding</span><span class="op">)</span>,
            sd <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">mean_bonding</span><span class="op">)</span>,
            n <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/context.html">n</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://rdrr.io/r/base/as.data.frame.html">as.data.frame</a></span><span class="op">(</span><span class="op">)</span> <span class="co"># Doesn't work well with tibbles</span>

<span class="co"># Save values for Control</span>
<span class="va">Control_mean</span> <span class="op">&lt;-</span> <span class="va">Brandt_summary</span><span class="op">[</span><span class="fl">1</span>, <span class="fl">2</span><span class="op">]</span>
<span class="va">Control_sd</span> <span class="op">&lt;-</span> <span class="va">Brandt_summary</span><span class="op">[</span><span class="fl">1</span>, <span class="fl">3</span><span class="op">]</span>
<span class="va">Control_n</span> <span class="op">&lt;-</span> <span class="va">Brandt_summary</span><span class="op">[</span><span class="fl">1</span>, <span class="fl">4</span><span class="op">]</span>

<span class="co"># Save values for Pain</span>
<span class="va">Pain_mean</span> <span class="op">&lt;-</span> <span class="va">Brandt_summary</span><span class="op">[</span><span class="fl">2</span>, <span class="fl">2</span><span class="op">]</span>
<span class="va">Pain_sd</span> <span class="op">&lt;-</span> <span class="va">Brandt_summary</span><span class="op">[</span><span class="fl">2</span>, <span class="fl">3</span><span class="op">]</span>
<span class="va">Pain_n</span> <span class="op">&lt;-</span> <span class="va">Brandt_summary</span><span class="op">[</span><span class="fl">2</span>, <span class="fl">4</span><span class="op">]</span></code></pre></div>
<p>Now we have our values, it is time to think about what values we will use for the boundaries. From the lecture, there are different strategies (this is a non-exhaustive list) to choosing and justifying your smallest effect size of interest boundaries:</p>
<ol style="list-style-type: decimal">
<li><p>Your understanding of the applications / mechanisms (e.g., a clinically meaningful decrease in pain).</p></li>
<li><p>Smallest effects from previous research (e.g., lower bound of individual study effect sizes or lower bound of a meta-analysis).</p></li>
<li><p>Small telescopes (the effect size the original study had 33% power to detect).</p></li>
</ol>
<p>For Bastian et al. (2014), they measured bonding on a 5-point Likert scale, so we might consider anything less than a one-point difference as too small to be practically meaningful for demonstration purposes. We can now enter these values into the TOSTER function.</p>
<div class="sourceCode" id="cb142"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Save as object and present with brackets around </span>
<span class="op">(</span><span class="va">Brandt_TOST</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://aaroncaldwell.us/TOSTERpkg/reference/tsum_TOST.html">tsum_TOST</a></span><span class="op">(</span>m1 <span class="op">=</span> <span class="va">Control_mean</span>, <span class="co"># Group 1: Control</span>
                         sd1 <span class="op">=</span> <span class="va">Control_sd</span>,
                         n1 <span class="op">=</span> <span class="va">Control_n</span>,
                         m2 <span class="op">=</span> <span class="va">Pain_mean</span>, <span class="co"># Group 2: Pain</span>
                         sd2 <span class="op">=</span> <span class="va">Pain_sd</span>,
                         n2 <span class="op">=</span> <span class="va">Pain_n</span>,
                         hypothesis <span class="op">=</span> <span class="st">"EQU"</span>, <span class="co"># Equivalence test rather than minimal effects test</span>
                         low_eqbound <span class="op">=</span> <span class="op">-</span><span class="fl">1</span>, <span class="co"># Our lower and upper equivalence bounds</span>
                         high_eqbound <span class="op">=</span> <span class="fl">1</span>,
                         eqbound_type <span class="op">=</span> <span class="st">"raw"</span>, <span class="co"># We can specify raw or standardised values</span>
                         alpha <span class="op">=</span> <span class="fl">0.05</span><span class="op">)</span><span class="op">)</span> <span class="co"># We could change alpha from the default</span></code></pre></div>
<pre><code>## 
## Welch Modified Two-Sample t-Test
## Hypothesis Tested: Equivalence
## Equivalence Bounds (raw):-1.000 &amp; 1.000
## Alpha Level:0.05
## The equivalence test was non-significant, t(51.7) = 1.484, p = 7.2e-02
## The null hypothesis test was significant, t(51.7) = -2.022, p = 4.84e-02
## NHST: reject null significance hypothesis that the effect is equal to zero 
## TOST: don't reject null equivalence hypothesis
## 
## TOST Results 
##                    t        SE       df      p.value
## t-test     -2.021774 0.2852542 51.69508 4.839002e-02
## TOST Lower  1.483871 0.2852542 51.69508 7.195754e-02
## TOST Upper -5.527420 0.2852542 51.69508 5.390001e-07
## 
## Effect Sizes 
##                 estimate        SE  lower.ci    upper.ci conf.level
## Raw           -0.5767196 0.2852542 -1.054483 -0.09895642        0.9
## Hedges' g(av) -0.5422288 0.2830491 -1.024025 -0.09475207        0.9
## 
## Note: SMD confidence intervals are an approximation. See vignette("SMD_calcs").</code></pre>
<p>We have quite a lot of output to break down and there are essentially three parts.</p>
<p>The first provides an overview of the two one-sided test procedure you applied and what you can conclude from it. After confirming your inputs, you have one t-test for the equivalence test and one traditional t-test. You only get one for the equivalence test as both must be significant to conclude the effect was statistically equivalent, so you typically report the largest <em>p</em>-value as if that is significant, the other test will be lower. You then get two one sentence statements on what you can conclude from the tests. For this example, the traditional t-test was significant to suggest we can reject the point-null hypothesis, but the equivalence test was not statistically equivalent for our choice of boundaries.</p>
<p>The second provides the full output for all three t-tests: the traditional t-test and the two one-sided tests. This is more helpful for reporting as you can produce the full t-test statistics, for example the one-sided test with the largest p-value would be: <em>t</em> (51.70) = 1.48, <em>p</em> = .07. The degrees of freedom is not an integer as it produces the Welch version of the t-test (<a href="http://www.rips-irsp.com/articles/10.5334/irsp.82/">Delacre et al., 2017</a>). If you really want the student t-test, you can use the argument <code>var.equal = TRUE</code>.</p>
<p>Finally, the third provides estimates and 90% confidence intervals for the effect size in raw and standardised units. This is the estimate of your effect size and what you can see in the plots below. Remember, you get a 90% confidence interval as the specified alpha is .05 but you are performing two one-sided tests. So, the overall confidence level is .90.</p>
<p>For the t-test TOSTER function, we do not get an accompanying plot by default. However, since we saved the model object, we can call a plot to visualise the equivalence testing procedure.</p>
<div class="sourceCode" id="cb144"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">Brandt_TOST</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="appendix-b-equivalence-testing_files/figure-html/Brandt%20TOST%20plot-1.png" width="100%" style="display: block; margin: auto;"></div>
<p>This plots both the raw and standardised effects from the final part of the output above. The vertical dashed lines represent your user-defined bounds for the smallest effect size of interest. The circle and thick black line at the bottom of each panel represent the estimate for the effect size and its 90% confidence interval. This is what you are using for the equivalence testing procedure. If the confidence interval is entirely within your bounds, the test is statistically equivalent. However, in this scenario, the confidence interval crosses the lower bound, visually reinforcing how the largest one-sided test above was not statistically significant.</p>
<p>As additional information, note there are different confidence levels plotted above and colour coded. The confidence interval bar reaches the end of the green region for 90%. You also have two further levels of 95% and 99.9% confidence intervals.</p>
</div>
<div id="correlation" class="section level2" number="12.2">
<h2>
<span class="header-section-number">B.2</span> Correlation<a class="anchor" aria-label="anchor" href="#correlation"><i class="fas fa-link"></i></a>
</h2>
</div>
<div id="meta-analysis" class="section level2" number="12.3">
<h2>
<span class="header-section-number">B.3</span> Meta-analysis<a class="anchor" aria-label="anchor" href="#meta-analysis"><i class="fas fa-link"></i></a>
</h2>
</div>
<div id="further-reading" class="section level2" number="12.4">
<h2>
<span class="header-section-number">B.4</span> Further reading<a class="anchor" aria-label="anchor" href="#further-reading"><i class="fas fa-link"></i></a>
</h2>
<p>In this appendix, we mainly focused on the practical part of applying equivalence testing in R. Possibly the hardest part of this technique is choosing and justifying your equivalence bounds. Therefore, there are some recommendations for further reading to explore more of the topic.</p>
<ul>
<li><p><a href="https://lakens.github.io/statistical_inferences/equivalencetest.html">Lakens (2023)</a> has an online open access textbook on improving your statistical inferences. Chapter 9 focuses on equivalence testing and explains different methods for setting your smallest effect size of interest.</p></li>
<li><p><a href="https://journals.sagepub.com/doi/10.1177/1948550617697177">Lakens (2017)</a> and <a href="https://journals.sagepub.com/doi/10.1177/2515245918770963">Lakens et al. (2018)</a> have two tutorial articles where they walk through applying and reporting equivalence testing.</p></li>
<li><p><a href="https://journal.trialanderror.org/pub/attentionalsmoker/release/2">Bartlett et al. (2022)</a> provides a published example of equivalence testing if you want to see how it can look and be reported in a results section.</p></li>
</ul>
</div>
</div>
<script>

/* update total correct if #webex-total_correct exists */
update_total_correct = function() {
  console.log("webex: update total_correct");

  if (t = document.getElementById("webex-total_correct")) {
    var correct = document.getElementsByClassName("webex-correct").length;
    var solvemes = document.getElementsByClassName("webex-solveme").length;
    var radiogroups = document.getElementsByClassName("webex-radiogroup").length;
    var selects = document.getElementsByClassName("webex-select").length;

    t.innerHTML = correct + " of " + (solvemes + radiogroups + selects) + " correct";
  }
}

/* webex-solution button toggling function */
b_func = function() {
  console.log("webex: toggle hide");

  var cl = this.parentElement.classList;
  if (cl.contains('open')) {
    cl.remove("open");
  } else {
    cl.add("open");
  }
}

/* function for checking solveme answers */
solveme_func = function(e) {
  console.log("webex: check solveme");

  var real_answers = JSON.parse(this.dataset.answer);
  var my_answer = this.value;
  var cl = this.classList;
  if (cl.contains("ignorecase")) {
    my_answer = my_answer.toLowerCase();
  }
  if (cl.contains("nospaces")) {
    my_answer = my_answer.replace(/ /g, "")
  }

  if (my_answer == "") {
    cl.remove("webex-correct");
    cl.remove("webex-incorrect");
  } else if (real_answers.includes(my_answer)) {
    cl.add("webex-correct");
    cl.remove("webex-incorrect");
  } else {
    cl.add("webex-incorrect");
    cl.remove("webex-correct");
  }

  // match numeric answers within a specified tolerance
  if(this.dataset.tol > 0){
    var tol = JSON.parse(this.dataset.tol);
    var matches = real_answers.map(x => Math.abs(x - my_answer) < tol)
    if (matches.reduce((a, b) => a + b, 0) > 0) {
      cl.add("webex-correct");
    } else {
      cl.remove("webex-correct");
    }
  }

  // added regex bit
  if (cl.contains("regex")){
    answer_regex = RegExp(real_answers.join("|"))
    if (answer_regex.test(my_answer)) {
      cl.add("webex-correct");
    }
  }

  update_total_correct();
}

/* function for checking select answers */
select_func = function(e) {
  console.log("webex: check select");

  var cl = this.classList

  /* add style */
  cl.remove("webex-incorrect");
  cl.remove("webex-correct");
  if (this.value == "answer") {
    cl.add("webex-correct");
  } else if (this.value != "blank") {
    cl.add("webex-incorrect");
  }

  update_total_correct();
}

/* function for checking radiogroups answers */
radiogroups_func = function(e) {
  console.log("webex: check radiogroups");

  var checked_button = document.querySelector('input[name=' + this.id + ']:checked');
  var cl = checked_button.parentElement.classList;
  var labels = checked_button.parentElement.parentElement.children;

  /* get rid of styles */
  for (i = 0; i < labels.length; i++) {
    labels[i].classList.remove("webex-incorrect");
    labels[i].classList.remove("webex-correct");
  }

  /* add style */
  if (checked_button.value == "answer") {
    cl.add("webex-correct");
  } else {
    cl.add("webex-incorrect");
  }

  update_total_correct();
}

window.onload = function() {
  console.log("webex onload");
  /* set up solution buttons */
  var buttons = document.getElementsByTagName("button");

  for (var i = 0; i < buttons.length; i++) {
    if (buttons[i].parentElement.classList.contains('webex-solution')) {
      buttons[i].onclick = b_func;
    }
  }

  /* set up webex-solveme inputs */
  var solveme = document.getElementsByClassName("webex-solveme");

  for (var i = 0; i < solveme.length; i++) {
    /* make sure input boxes don't auto-anything */
    solveme[i].setAttribute("autocomplete","off");
    solveme[i].setAttribute("autocorrect", "off");
    solveme[i].setAttribute("autocapitalize", "off");
    solveme[i].setAttribute("spellcheck", "false");
    solveme[i].value = "";

    /* adjust answer for ignorecase or nospaces */
    var cl = solveme[i].classList;
    var real_answer = solveme[i].dataset.answer;
    if (cl.contains("ignorecase")) {
      real_answer = real_answer.toLowerCase();
    }
    if (cl.contains("nospaces")) {
      real_answer = real_answer.replace(/ /g, "");
    }
    solveme[i].dataset.answer = real_answer;

    /* attach checking function */
    solveme[i].onkeyup = solveme_func;
    solveme[i].onchange = solveme_func;

    $(solveme[i]).after(" <span class='webex-icon'></span>");
  }

  /* set up radiogroups */
  var radiogroups = document.getElementsByClassName("webex-radiogroup");
  for (var i = 0; i < radiogroups.length; i++) {
    radiogroups[i].onchange = radiogroups_func;
  }

  /* set up selects */
  var selects = document.getElementsByClassName("webex-select");
  for (var i = 0; i < selects.length; i++) {
    selects[i].onchange = select_func;
    $(selects[i]).after(" <span class='webex-icon'></span>");
  }

  update_total_correct();
}

</script><script>
$( document ).ready(function() {
  var cite = ' ';
  var psyteachr = ' <a href="https://psyteachr.github.io/"><img src="images/logos/psyteachr_logo.png" style="height: 31px; color: white;" alt="psyTeachR: Reproducible Research" /></a>';
  var license = ' <a rel="license" href="https://creativecommons.org/licenses/by-sa/4.0/" target="blank"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png"></a>';

  $("footer div.row div:eq(1) p").html(
    psyteachr + license + cite
  );

  // open rdrr links externally
  $("a[href^='https://rdrr.io']").click(function(){
    window.open(this.href);
    return false;
  });

  // visible second sidebar in mobile
  function move_sidebar() {
    var w = window.innerWidth;
    if (w < 992) {
      $("#toc").appendTo($("#main-nav"));
    } else {
      $("#toc").appendTo($("div.sidebar-chapter"));
    }
  }
  move_sidebar();
  window.onresize = move_sidebar;
});
</script><div class="chapter-nav">
<div class="prev"><a href="installing-r.html"><span class="header-section-number">A</span> Installing R</a></div>
<div class="next"><a href="conventions.html"><span class="header-section-number">C</span> Conventions</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#Frequentist-Equivalence"><span class="header-section-number">B</span> Frequentist Equivalence Testing</a></li>
<li><a class="nav-link" href="#t-tests"><span class="header-section-number">B.1</span> t-tests</a></li>
<li><a class="nav-link" href="#correlation"><span class="header-section-number">B.2</span> Correlation</a></li>
<li><a class="nav-link" href="#meta-analysis"><span class="header-section-number">B.3</span> Meta-analysis</a></li>
<li><a class="nav-link" href="#further-reading"><span class="header-section-number">B.4</span> Further reading</a></li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
<li><a id="book-source" href="https://github.com/psyteachr/statsresdesign/blob/master/book/appendix-b-equivalence-testing.Rmd">View source <i class="fab fa-github"></i></a></li>
          <li><a id="book-edit" href="https://github.com/psyteachr/statsresdesign/edit/master/book/appendix-b-equivalence-testing.Rmd">Edit this page <i class="fab fa-github"></i></a></li>
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>Statistics and Research Design</strong>" was written by James Bartlett. It was last built on 2023-04-13.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script><script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>
</html>
