<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Chapter 1 Introduction to Linear Regression | Statistics and Research Design</title>
<meta name="author" content="James Bartlett">
<meta name="description" content="In this chapter, we start with the foundations of linear regression. We will be focusing on simple linear regression where you have one predictor variable and one outcome. You will apply...">
<meta name="generator" content="bookdown 0.37 with bs4_book()">
<meta property="og:title" content="Chapter 1 Introduction to Linear Regression | Statistics and Research Design">
<meta property="og:type" content="book">
<meta property="og:url" content="https://psyteachr.github.io/statsresdesign/introduction-to-linear-regression.html">
<meta property="og:image" content="https://psyteachr.github.io/statsresdesign/images/logos/logo.png">
<meta property="og:description" content="In this chapter, we start with the foundations of linear regression. We will be focusing on simple linear regression where you have one predictor variable and one outcome. You will apply...">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="Chapter 1 Introduction to Linear Regression | Statistics and Research Design">
<meta name="twitter:description" content="In this chapter, we start with the foundations of linear regression. We will be focusing on simple linear regression where you have one predictor variable and one outcome. You will apply...">
<meta name="twitter:image" content="https://psyteachr.github.io/statsresdesign/images/logos/logo.png">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><script src="libs/bs3compat-0.6.1/transition.js"></script><script src="libs/bs3compat-0.6.1/tabs.js"></script><script src="libs/bs3compat-0.6.1/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><script src="libs/kePrint-0.0.1/kePrint.js"></script><link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<!-- Global site tag (gtag.js) - Google Analytics --><script async src="https://www.googletagmanager.com/gtag/js?id=G-6NP3MF25W3"></script><script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-6NP3MF25W3');
    </script><script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- CSS --><style type="text/css">
    
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  </style>
<style type="text/css">
    /* Used with Pandoc 2.11+ new --citeproc when CSL is used */
    div.csl-bib-body { }
    div.csl-entry {
      clear: both;
        }
    .hanging div.csl-entry {
      margin-left:2em;
      text-indent:-2em;
    }
    div.csl-left-margin {
      min-width:2em;
      float:left;
    }
    div.csl-right-inline {
      margin-left:2em;
      padding-left:1em;
    }
    div.csl-indent {
      margin-left: 2em;
    }
  </style>
<link rel="stylesheet" href="include/psyteachr.css">
<link rel="stylesheet" href="include/webex.css">
<link rel="stylesheet" href="include/style.css">
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="">Statistics and Research Design</a>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html">Overview</a></li>
<li><a class="active" href="introduction-to-linear-regression.html"><span class="header-section-number">1</span> Introduction to Linear Regression</a></li>
<li><a class="" href="multiple-linear-regression.html"><span class="header-section-number">2</span> Multiple Linear Regression</a></li>
<li><a class="" href="introduction-to-generalised-linear-models.html"><span class="header-section-number">3</span> Introduction to Generalised Linear Models</a></li>
<li><a class="" href="introduction-to-bayesian-hypothesis-testing.html"><span class="header-section-number">4</span> Introduction to Bayesian Hypothesis Testing</a></li>
<li><a class="" href="introduction-to-bayesian-estimation.html"><span class="header-section-number">5</span> Introduction to Bayesian Estimation</a></li>
<li><a class="" href="introduction-to-linear-mixed-effects-models.html"><span class="header-section-number">6</span> Introduction to Linear Mixed Effects Models</a></li>
<li class="book-part">Appendices</li>
<li><a class="" href="installing-r.html"><span class="header-section-number">A</span> Installing R</a></li>
<li><a class="" href="conventions.html"><span class="header-section-number">B</span> Conventions</a></li>
<li><a class="" href="license.html">License</a></li>
<li><a class="" href="references.html">References</a></li>
</ul>

        <div class="book-extra">
          <p><a id="book-repo" href="https://github.com/psyteachr/statsresdesign">View book source <i class="fab fa-github"></i></a></p>
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="introduction-to-linear-regression" class="section level1" number="1">
<h1>
<span class="header-section-number">1</span> Introduction to Linear Regression<a class="anchor" aria-label="anchor" href="#introduction-to-linear-regression"><i class="fas fa-link"></i></a>
</h1>
<p>In this chapter, we start with the foundations of linear regression. We will be focusing on simple linear regression where you have one predictor variable and one outcome. You will apply continuous and categorical predictors to see how the interpretation changes, and start to explore parametric assumptions to make sure this kind of model is appropriate for your data.</p>
<div id="learning-objectives" class="section level2" number="1.1">
<h2>
<span class="header-section-number">1.1</span> Learning objectives<a class="anchor" aria-label="anchor" href="#learning-objectives"><i class="fas fa-link"></i></a>
</h2>
<p>By the end of this chapter, you should be able to:</p>
<ol style="list-style-type: decimal">
<li><p>Apply simple linear regression using <a href="introduction-to-linear-regression.html#LM_groups">one categorical predictor</a>.</p></li>
<li><p>Apply simple linear regression using <a href="introduction-to-linear-regression.html#LM_continuous">one continuous predictor</a>.</p></li>
<li><p>Evaluate whether your regression model meets parametric assumptions.</p></li>
<li><p>Report the results of your findings in APA style.</p></li>
</ol>
<p>To follow along to this chapter and try the code yourself, please download the data files we will be using in <a href="data/01_data.zip">this zip file</a>.</p>
</div>
<div id="packages-and-the-data-set" class="section level2" number="1.2">
<h2>
<span class="header-section-number">1.2</span> Packages and the data set<a class="anchor" aria-label="anchor" href="#packages-and-the-data-set"><i class="fas fa-link"></i></a>
</h2>
<p>We first need to load some packages and the data for this task. If you do not have any of the packages, make sure you install them first.</p>
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># load packages you need for these tasks</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Load data for this task</span></span>
<span><span class="va">zhang_data</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="st">"data/Zhang_data.csv"</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>condition <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">as.factor</a></span><span class="op">(</span><span class="va">condition</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<p>For the guided example, we will use unpublished data from Bartlett and Zhang who performed a direct replication of <span class="citation">Irving et al. (<a href="references.html#ref-irving_correcting_2022">2022</a>)</span>. They studied statistical misinformation, meaning a scientific result that people think is true, but later turns out to be false. Their specific focus was on mistaking correlational evidence for causal evidence and how you can best correct misinformation. Their research question and ours for the replication was: Can you correct statistical misinformation through debunking? The hypothesis was: There will be fewer causal inferences in the correction group compared to the no correction group</p>
<p>For an overview of the method, 129 participants completed a continuous influence paradigm where participants read a fictious newspaper article one sentence at a time about a causal link between cognitive decline and watching TV in older adults. There is one independent variable to randomly allocate participants into one of two groups:</p>
<ol style="list-style-type: decimal">
<li><p>The correction group (group <code>1</code> in the data) had one sentence saying: “The lead author has since specified that the results have been misrepresented and that TV screen time has not yet been found to cause cognitive decline. Only a correlation has been found…”</p></li>
<li><p>The no correction group (group <code>0</code> in the data) alternatively said: “The lead author of the study could not be reached for comment”</p></li>
</ol>
<p>Participants then completed five free-text questions asking them about information in the study. Their responses were manually coded and received a 1 if they made a mistaken causal inference, or a 0 if they did not make. We then took the sum of the five coded questions to tell us the number of mistaken causal inferences.</p>
<p>This means we have one between-subjects independent variable of their correction group for a predictor (<code>condition</code>), and one outcome of the sum mistaken causal inferences which can range between 0 and 5 (<code>harsh_DV1_sum</code>). We can apply simple linear regression to test our hypothesis using this dataset.</p>
<div id="exploratory-data-analysis" class="section level3" number="1.2.1">
<h3>
<span class="header-section-number">1.2.1</span> Exploratory data analysis<a class="anchor" aria-label="anchor" href="#exploratory-data-analysis"><i class="fas fa-link"></i></a>
</h3>
<p>When starting any data analysis, it is important to visualise the data for some exploratory data analysis. Using the skills you developed in data skills for reproducible research, we can explore the data to understand its properties and look for potential patterns. At first, this might be very quick plots using a few lines of <code class="package">ggplot2</code> code.</p>
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">zhang_data</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">condition</span>, y <span class="op">=</span> <span class="va">harsh_DV1_sum</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_boxplot.html">geom_boxplot</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="01-LM1_files/figure-html/unnamed-chunk-2-1.png" width="100%" style="display: block; margin: auto;"></div>
<p>From a simple boxplot, we can get a quick understanding of how the responses are distributed for each condition. Remember 0 represents the no correction group and 1 represents the correction group, so it looks like people in the correction group made fewer mistaken causal inferences than people in the no correction group.</p>
<p>When we have more time, you can customise the plot to be much more publication ready with informative titles etc. For example, we can create a violin plot showing the distribution of responses with the mean and 95% confidence superimposed.</p>
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">zhang_data</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">condition</span>, y <span class="op">=</span> <span class="va">harsh_DV1_sum</span>, fill <span class="op">=</span> <span class="va">condition</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_violin.html">geom_violin</a></span><span class="op">(</span>alpha <span class="op">=</span> <span class="fl">.6</span>, trim <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/stat_summary.html">stat_summary</a></span><span class="op">(</span>fun <span class="op">=</span> <span class="st">"mean"</span>, geom <span class="op">=</span> <span class="st">"point"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/stat_summary.html">stat_summary</a></span><span class="op">(</span>fun.data <span class="op">=</span> <span class="st">"mean_cl_normal"</span>, geom <span class="op">=</span> <span class="st">"errorbar"</span>, width <span class="op">=</span> <span class="fl">.1</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_viridis.html">scale_fill_viridis_d</a></span><span class="op">(</span>option <span class="op">=</span> <span class="st">"E"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_continuous.html">scale_y_continuous</a></span><span class="op">(</span>name <span class="op">=</span> <span class="st">"Sum of Causal Inferences (0-5)"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_discrete.html">scale_x_discrete</a></span><span class="op">(</span>name <span class="op">=</span> <span class="st">"Condition"</span>, label <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"No Correction"</span>, <span class="st">"Correction"</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/guides.html">guides</a></span><span class="op">(</span>fill <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_minimal</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="01-LM1_files/figure-html/unnamed-chunk-3-1.png" width="100%" style="display: block; margin: auto;"></div>
</div>
</div>
<div id="LM_groups" class="section level2" number="1.3">
<h2>
<span class="header-section-number">1.3</span> Simple linear regression for one categorical predictor<a class="anchor" aria-label="anchor" href="#LM_groups"><i class="fas fa-link"></i></a>
</h2>
<p>Now you understand the data a little better, it is time to apply our modelling technique to address our research question and hypothesis. We want to know whether participants made fewer mistaken causal inferences in the correction group compared to the non-correction group.</p>
<p>Below, we use <code>condition</code> as the predictor variable (which is categorical with two groups of 0 and 1) and <code>harsh_DV1_sum</code> as the outcome variable. The first step is to create an object (<code>lm_condition</code>) for the linear model.</p>
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">lm_condition</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">harsh_DV1_sum</span> <span class="op">~</span> <span class="va">condition</span>, data <span class="op">=</span> <span class="va">zhang_data</span><span class="op">)</span></span></code></pre></div>
<p>The function <code><span><span class="fu"><a target="_blank" href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="op">)</span></span></code> is built into R and is very flexible for creating linear regression models. The first argument is to specify a formula which defines our model. The first component (<code>harsh_DV1_sum</code>) is our outcome variable for what we are interested in modelling. The tilde (~) separates the equation, where everything on the right is your predictor variable(s). In simple linear regression, we just have one which is <code>condition</code> in our model here. This is saying we want to predict <code>harsh_DV1_sum</code> as our outcome from <code>condition</code> as our predictor. We then specify the data frame we want to use.</p>
<p>When you create this object, it stores a bunch of information, but does not really tell us all the statistics we expect. If you simply print the object in the console, it will tell you the intercept and coefficient(s), but none of the model fitting nor null hypothesis significance testing. If you look at the object in the R environment, you will see it is a list containing loads of elements. It stores things like the model, the residuals, and other information you can use.</p>
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">lm_condition</span></span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = harsh_DV1_sum ~ condition, data = zhang_data)
## 
## Coefficients:
## (Intercept)   condition1  
##      2.0625      -0.7856</code></pre>
<p>To get that extra information, we need to call the <code><span><span class="fu"><a target="_blank" href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="op">)</span></span></code> function around the linear model object to explore its properties like estimates and model fit.</p>
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">lm_condition</span><span class="op">)</span></span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = harsh_DV1_sum ~ condition, data = zhang_data)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -2.0625 -1.0625 -0.0625  0.7231  3.7231 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   2.0625     0.1424  14.486  &lt; 2e-16 ***
## condition1   -0.7856     0.2006  -3.917 0.000146 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 1.139 on 127 degrees of freedom
## Multiple R-squared:  0.1078, Adjusted R-squared:  0.1007 
## F-statistic: 15.34 on 1 and 127 DF,  p-value: 0.0001458</code></pre>
<p>To walk through the output, <code>Call:</code> summarises the model you specified. <code>Residuals:</code> provides a summary of the model residuals. We will come back to those later. <code>Coefficients:</code> provides our model output, this time with inferential statistics. The two key lines are:</p>
<ol style="list-style-type: decimal">
<li><p><code>(Intercept)</code> - This is the value of the outcome when our predictor is set to 0 - the reference group. Since our predictor includes two groups coded 0 and 1, this means the intercept represents the number of mistaken causal inferences for the no correction group. They recalled a mean of 2.06 mistaken causal inferences. You get a <em>p</em>-value for this, but in isolation it is not too useful. It just compares the intercept estimate to 0 which typically you are not interested in.</p></li>
<li><p><code>condition1</code> - This is the slope or coefficient. This is the change in the outcome for every 1 unit change in the predictor. Given we have a categorical predictor, it is the change from the reference group 0 (no correction) to the target group 1 (correction), meaning its essentially the mean difference between groups. It is -0.79 here, so we estimate the correction group made on average 0.79 fewer mistaken causal inferences than the no correction group. Looking at the <em>p</em>-value, this is statistically significant, suggesting we can reject the null hypothesis and conclude there is an effect here.</p></li>
</ol>
<div class="info">
<p>Does it matter if the slope/coefficient is positive or negative? When you have two groups, it does not really matter which group is the reference and which is the target, you just need to know which is which for interpretation. In the output, R appends the target group to the predictor name (<code>condition1</code>). We typically use the 0 and 1 system as its closely aligned with the slope interpretation, but you do not need it. If you used character variables, it will still work, but it will default to alphabetical order unless you turn it into a factor.</p>
<p>When it comes to continuous predictors later, the sign <em>does</em> matter. A positive slope would mean an increase in the predictor is associated with increased values of your outcome. A negative slope would mean an increase in the predictor is associated with decreased values of your outcome.</p>
</div>
<p>At the bottom of the model output, you then get the fit statistics. Multiple <span class="math inline">\(R^2\)</span> tells you how much variance in your outcome your predictor(s) explain. Adjusted <span class="math inline">\(R^2\)</span> tends to be more conservative as it adjusts for the number of predictors in the model, but they will be very similar when you have one predictor. Adjusted <span class="math inline">\(R^2\)</span> is 0.10, suggesting <code>condition</code> explains 10% of the variance in <code>harsh_DV1_sum</code>. Remember in psychology / life sciences, this will be on the smaller side as we are studying messier / more complicated things.</p>
<p>Finally, we have the model fit statistics to tell us whether the model explains a significant amount of variance in the outcome. With one predictor, the <em>p</em>-value next to the coefficient and next to the model fit will be almost identical, but they represent two things when it comes to multiple linear regression. The F-statistic is 15.34, the model degrees of freedom is 1, the residual degrees of freedom is 127, and the <em>p</em>-value is <em>p</em> = .0001.</p>
<p>One thing is missing here. By default, you do not receive confidence intervals for model estimates, but you can call them using the linear model object. R comes with a function for calculating confidence intervals from model objects called <code><span><span class="fu"><a target="_blank" href="https://rdrr.io/r/stats/confint.html">confint</a></span><span class="op">(</span><span class="op">)</span></span></code>.</p>
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/confint.html">confint</a></span><span class="op">(</span><span class="va">lm_condition</span><span class="op">)</span></span></code></pre></div>
<pre><code>##                 2.5 %     97.5 %
## (Intercept)  1.780761  2.3442392
## condition1  -1.182481 -0.3886729</code></pre>
<p>It's normally a good idea to report all three pieces of inferential information, the point estimate (-0.79), the interval estimate (-1.18, -0.39), and hypothesis testing (<em>p</em> &lt; .001). So, to bring it back to the research question and hypothesis, it looks like the replication supported our prediction. Participants in the correction group provided fewer causal inferences than those in the no correction group (<span class="math inline">\(b_1\)</span> = -0.79, 95% CI = [-1.18, -0.39], <em>p</em> &lt; .001). In your reports, you would then have to think about whether that effect size is consistent with previous research and put your findings in context.</p>
<div id="checking-the-statistical-assumptions" class="section level3" number="1.3.1">
<h3>
<span class="header-section-number">1.3.1</span> Checking the statistical assumptions<a class="anchor" aria-label="anchor" href="#checking-the-statistical-assumptions"><i class="fas fa-link"></i></a>
</h3>
<p>For the inferential statistics to work as intended, the model makes certain assumptions about the data you are putting into it. They work by assuming a given probability distribution and the accuracy of the inferences depends on how sensible this assumption is. Remember these functions will always work even if the numbers you enter are nonsense, so its important for you as the researcher to recognise when its appropriate to use these statistics.</p>
<p>As a reminder, the assumptions for simple linear regression are:</p>
<ol style="list-style-type: decimal">
<li><p>The outcome is interval/ratio level data.</p></li>
<li><p>The predictor variable is interval/ratio or categorical (with two levels at a time).</p></li>
<li><p>All values of the outcome variable are independent (i.e., each score should come from a different participant/observation).</p></li>
<li><p>The predictors have non-zero variance.</p></li>
<li><p>The relationship between the outcome and predictor is linear.</p></li>
<li><p>The residuals should be normally distributed.</p></li>
<li><p>There should be homoscedasticity.</p></li>
</ol>
<p>Assumptions 1-4 are pretty straight forward as they relate to your understanding of the design or a simple check on the data for non-zero variance.</p>
<p>When you have a categorical predictor, the linearity assumption is met by default. As you are comparing two groups, there can only be a straight line between the two of them. We will come back to this for the continuous predictors.</p>
<p>You can get a series of diagnostic plots by calling the <code><span><span class="fu"><a target="_blank" href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="op">)</span></span></code> function on the model object. For a categorical predictor, some of these do not work very well, but it will be more useful for continuous predictors and multiple linear regression models.</p>
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">lm_condition</span><span class="op">)</span></span></code></pre></div>
<p><img src="01-LM1_files/figure-html/unnamed-chunk-8-1.png" width="100%" style="display: block; margin: auto;"><img src="01-LM1_files/figure-html/unnamed-chunk-8-2.png" width="100%" style="display: block; margin: auto;"><img src="01-LM1_files/figure-html/unnamed-chunk-8-3.png" width="100%" style="display: block; margin: auto;"><img src="01-LM1_files/figure-html/unnamed-chunk-8-4.png" width="100%" style="display: block; margin: auto;"></p>
<p>The first plot is normally useful for checking homoscedasticity, but its difficult to spot patterns for two groups as all the data points line up vertically. To meet the assumption, you want the variance of the outcome to be roughly equal across the predictor. The third plot provides similar information, but it plots standardised residuals instead.</p>
<p>The second plot is good for normality and provides an alternative way of plotting the residuals. On the y-axis, you have the model residuals. On the x-axis, you have the theoretical quantiles you would expect if its normally distributed. To meet the assumption, the points should roughly follow the straight line. Red flags would be substantially deviating from the line or snaking around in an "s" or "c" shape.</p>
<p>Finally, the fourth plot is useful for spotting influential observations - a type of outlier. The definition here is known as leverage, which means how the coefficient would change if we removed a given data point. Large leverage values would mean the coefficient would change more dramatically, so its potentially an outlier. You cannot see it on this plot, but high leverage outliers would appear outside a series of red dashed lines.</p>
<p>In summary, there are no major red flags here. These checks rely on your subjective opinion, so you are looking for major deviations which would question whether using this model is appropriate or not. A general approach is if you squint and it looks fine, its probably fine. Major deviations tend to be pretty obvious.</p>
</div>
</div>
<div id="LM_continuous" class="section level2" number="1.4">
<h2>
<span class="header-section-number">1.4</span> Simple linear regression with one continuous predictor<a class="anchor" aria-label="anchor" href="#LM_continuous"><i class="fas fa-link"></i></a>
</h2>
<p>We have established how to run linear regression using one categorical predictor, but its also important to make sure you understand how to interpret the results of a continuous predictor.</p>
<p>In the Bartlett and Zhang data, there is not really a useful continuous predictor as we were interested in the effect of condition, but we can explore whether <code>age</code> is associated with the number of mistaken causal inferences. Maybe we expect older participants to make more mistakes.</p>
<p>Walking through the steps again, we can plot the data for some exploratory data analysis and check for initial patterns.</p>
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">zhang_data</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">age</span>, y <span class="op">=</span> <span class="va">harsh_DV1_sum</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_smooth.html">geom_smooth</a></span><span class="op">(</span>method <span class="op">=</span> <span class="st">"lm"</span><span class="op">)</span> <span class="co"># add a line of best fit using linear regression</span></span></code></pre></div>
<div class="inline-figure"><img src="01-LM1_files/figure-html/unnamed-chunk-9-1.png" width="100%" style="display: block; margin: auto;"></div>
<p>There is maybe a subtle negative relationship where there are fewer mistaken causal inferences in older participants, but it does not look very strong.</p>
<p>We can test the relationship by creating an object for the linear model and getting our summary.</p>
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">lm_age</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">harsh_DV1_sum</span> <span class="op">~</span> <span class="va">age</span>, data <span class="op">=</span> <span class="va">zhang_data</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">lm_age</span><span class="op">)</span></span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = harsh_DV1_sum ~ age, data = zhang_data)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -1.8316 -0.7318  0.2016  0.5927  3.2349 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  1.998027   0.359549   5.557 1.54e-07 ***
## age         -0.008319   0.008628  -0.964    0.337    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 1.201 on 127 degrees of freedom
## Multiple R-squared:  0.007268,   Adjusted R-squared:  -0.0005485 
## F-statistic: 0.9298 on 1 and 127 DF,  p-value: 0.3367</code></pre>
<p>All the information here is the same as before, but we are interested in how the interpretation changes. Remember the intercept represents the outcome when the predictor is set to 0, and the slope/coefficient is how we expect the outcome to change for every 1 unit change in the predictor.</p>
<p>Here, the intercept can be less useful than for categorical predictors. When age is set to 0, we would expect people to make 1.998 mistaken causal inferences. In isolation, this might not sound super useful as we would not be able to have participants at 0 year's old. We will come back to this shortly for how to make the intercept more interpretable.</p>
<p><code>age</code> is then our slope/coefficient and tells us how we expect the number of mistaken causal inferences to change for every 1 unit change in age. The units are unstandardised, meaning they depend on your scale of measurement, here being age in years. It is a negative predictor, meaning for every 1 year increase in age, we would expect people to make 0.008 fewer causal inferences. Combined with the <em>p</em>-value of .337, it does not appear to have a significant effect on our outcome as its non-significant assuming an alpha of .05.</p>
<p>We can get the confidence intervals for the estimates the same as before, showing we expect the slope to range from -0.025 to 0.009, so its consistent with a small negative relationship to a very small positive relationship, hence the lack of confidence in it as a predictor.</p>
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/confint.html">confint</a></span><span class="op">(</span><span class="va">lm_age</span><span class="op">)</span></span></code></pre></div>
<pre><code>##                   2.5 %      97.5 %
## (Intercept)  1.28654390 2.709509824
## age         -0.02539211 0.008753155</code></pre>
<p>Likewise, the model fit statistics shows we did not explain a significant amount of variance in the outcome. <span class="math inline">\(R^2\)</span> is essentially 0, with adjusted <span class="math inline">\(R^2\)</span> a negative value. You would just round to 0 though as a negative value does not make sense. Only the adjusted <span class="math inline">\(R^2\)</span> can be negative when it adds the correction, otherwise its impossible and would stop at 0.</p>
<div id="centering-continuous-predictors" class="section level3" number="1.4.1">
<h3>
<span class="header-section-number">1.4.1</span> Centering continuous predictors<a class="anchor" aria-label="anchor" href="#centering-continuous-predictors"><i class="fas fa-link"></i></a>
</h3>
<p>One way to make the intercept more interpretable is by centering the predictor. This means you subtract each participant's score from the mean of all the participants scores - kind of like the residuals. This means the variable will now have a mean of 0 for the center point and participant's values for age will be spread around 0 instead of their original values. The relationship between the numbers is the same, but it shifts the center point.</p>
<div class="sourceCode" id="cb17"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">zhang_data</span> <span class="op">&lt;-</span> <span class="va">zhang_data</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>age_center <span class="op">=</span> <span class="va">age</span> <span class="op">-</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">age</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">zhang_data</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">age_center</span>, y <span class="op">=</span> <span class="va">harsh_DV1_sum</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_smooth.html">geom_smooth</a></span><span class="op">(</span>method <span class="op">=</span> <span class="st">"lm"</span><span class="op">)</span> <span class="co"># add a line of best fit using linear regression</span></span></code></pre></div>
<div class="inline-figure"><img src="01-LM1_files/figure-html/unnamed-chunk-12-1.png" width="100%" style="display: block; margin: auto;"></div>
<p>We can see its impact on the model below.</p>
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">lm_age_centre</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">harsh_DV1_sum</span> <span class="op">~</span> <span class="va">age_center</span>, data <span class="op">=</span> <span class="va">zhang_data</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">lm_age_centre</span><span class="op">)</span></span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = harsh_DV1_sum ~ age_center, data = zhang_data)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -1.8316 -0.7318  0.2016  0.5927  3.2349 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  1.666667   0.105782  15.756   &lt;2e-16 ***
## age_center  -0.008319   0.008628  -0.964    0.337    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 1.201 on 127 degrees of freedom
## Multiple R-squared:  0.007268,   Adjusted R-squared:  -0.0005485 
## F-statistic: 0.9298 on 1 and 127 DF,  p-value: 0.3367</code></pre>
<p>You will notice the slope/coefficient and model fit statistics are all identical. The only thing that has changed is the intercept. Remember the intercept is the value of the outcome when the predictor is set to 0, so now we have centered the predictor, the intercept represents the mean value of the predictor as 0. So, for the average age of participants, we expect people to make 1.67 mistaken causal inferences. Centering the predictor can help your interpretation when 0 would not naturally appear in the data.</p>
</div>
<div id="checking-the-statistical-assumptions-1" class="section level3" number="1.4.2">
<h3>
<span class="header-section-number">1.4.2</span> Checking the statistical assumptions<a class="anchor" aria-label="anchor" href="#checking-the-statistical-assumptions-1"><i class="fas fa-link"></i></a>
</h3>
<p>Now we have a continuous predictor, the <code><span><span class="fu"><a target="_blank" href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="op">)</span></span></code> function for checking the model assumptions now looks as intended.</p>
<div class="sourceCode" id="cb20"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">lm_age</span><span class="op">)</span></span></code></pre></div>
<p><img src="01-LM1_files/figure-html/unnamed-chunk-14-1.png" width="100%" style="display: block; margin: auto;"><img src="01-LM1_files/figure-html/unnamed-chunk-14-2.png" width="100%" style="display: block; margin: auto;"><img src="01-LM1_files/figure-html/unnamed-chunk-14-3.png" width="100%" style="display: block; margin: auto;"><img src="01-LM1_files/figure-html/unnamed-chunk-14-4.png" width="100%" style="display: block; margin: auto;"></p>
<p>Plots 1 and 3 are useful for checking homoscedasticity. We want the variance to be approximately equal across the range of predictor values. We are looking for a roughly straight red line and the dots to have an equal density across the x-axis.</p>
<p>Plot 2 is similar to the categorical predictor. We want the points to roughly follow the line to support the model residuals being approximately normal.</p>
<p>Finally, plot 4 would show high leverage observations that could be potentially problematic as outliers, but there is nothing flagged here.</p>
</div>
</div>
<div id="reporting-the-results-of-linear-regression" class="section level2" number="1.5">
<h2>
<span class="header-section-number">1.5</span> Reporting the results of linear regression<a class="anchor" aria-label="anchor" href="#reporting-the-results-of-linear-regression"><i class="fas fa-link"></i></a>
</h2>
<p>Now we have some results to go with, there are a few recommendations on how to communicate that information. In psychology (and other disciplines), we tend to follow the American Psychological Association (APA) formatting guidelines as they provide a comprehensive standardised style to make sure information is being reported as easily digestible and consistent as possible. You can see this PDF for a <a href="https://apastyle.apa.org/instructional-aids/numbers-statistics-guide.pdf" target="_blank">little cheat sheet for numbers and statistics</a>, but we will outline some key principles to ensure you provide your reader with enough information.</p>
<ol style="list-style-type: decimal">
<li><p>Explain to the reader what your linear regression model was. For example, what was your outcome and predictor variable?</p></li>
<li><p>Report descriptive statistics to help contextualise your findings. For example, the mean and standard deviation of your outcome for each group, or the mean/standard deviation for your outcome and continuous predictor.</p></li>
<li><p>Provide an appropriate data visualisation to help communciate key patterns to the reader. For example, a violin plot or violin-boxplot for comparing groups/conditions, or a scatterplot for the relationship between two continuous variables.</p></li>
<li><p>Report all three key inferential statistics concepts for the coefficient: the point estimate, the interval estimate, and the <em>p</em>-value for hypothesis testing. When you have multiple predictors, you might provide the full model results in a table, but when you have one, you typically focus on the slope/coefficient as your key effect size that helps address your research question and hypothesis. APA style rounds numbers to 2 decimal places when numbers can be bigger than 1, and 3 decimals with no leading zero when it cannot be bigger than 1.</p></li>
<li><p>Provide an overview of the model fit statistics for whether your model explained a significant amount of variance in your outcome.</p></li>
</ol>
<p>For the original example, I could summarise the findings as:</p>
<p>"We hypothesised that participants in the correction group would report fewer mistaken causal inferences than those in the no correction group. To test this hypothesis, we applied simple linear regression using correction condition as a predictor variable and the number of mistaken causal inferences as an outcome variable. Figure 1 below shows the difference between the two groups as a violin plot.</p>
<p>Our model explained a statistically significant amount of variance in our outcome (adjusted <span class="math inline">\(R^2\)</span> = .10, <em>F</em>(1, 127) = 15.34, <em>p</em> &lt; .001). Participants in the correction group provided a mean of 0.79 (95% CI = [0.39, 1.18], <em>p</em> &lt; .001) fewer mistaken causal inferences than those in the no correction group. The results supported our hypothesis where we expected correcting statistical misinformation would result in fewer mistaken causal inferences compared to not correcting misinformation."</p>
<div class="inline-figure"><img src="01-LM1_files/figure-html/unnamed-chunk-15-1.png" width="100%" style="display: block; margin: auto;"></div>
<div class="warning">
<p>You might notice I flipped the 95% confidence interval values around here. In this framework, the confidence intervals are symmetrical around the estimate, and the order will depend on whether its positive or negative. In the output, the values were negative as correction group was lower on the outcome, but when I worded the results like this I did not include the sign directly. So, I flipped the two values around as it looks more intuitive when the slope estimate does not have the sign in this context.</p>
</div>
</div>
<div id="independent-activity" class="section level2" number="1.6">
<h2>
<span class="header-section-number">1.6</span> Independent activity<a class="anchor" aria-label="anchor" href="#independent-activity"><i class="fas fa-link"></i></a>
</h2>
<p>Now you have followed along to a guided example, it is important you can transfer your knowledge to a new scenario. So, we have a new data set for you to try out your understanding of these techniques on. Follow the instructions below and answer the questions, you can then scroll down to the <a href="introduction-to-linear-regression.html#C1_solution">end of the chapter</a> to see the solution we based on the questions on.</p>
<p>For an independent activity, we will use data from <span class="citation">Dawtry et al. (<a href="references.html#ref-dawtry_why_2015">2015</a>)</span> who investigated how people can differently view an increase in wealth inequality. 305 participants completed measures like:</p>
<ul>
<li><p>Household and estimated population income ($)</p></li>
<li><p>Perceived fairness and satisfaction of the current system of wealth redistribution (1 extremely fair – 9 extremely unfair). The measure uses the mean of two scale items.</p></li>
<li><p>Attitudes on wealth redistribution (1 strongly disagree – 6 strongly agree). The measure uses the mean of four scale items.</p></li>
</ul>
<p>For this independent activity, you will create two simple linear regression models:</p>
<ol style="list-style-type: decimal">
<li><p>You will use perceived fairness and satisfaction (<code>fairness_satisfaction</code>) as the outcome and attitudes on wealth redistribution (<code>redistribution</code>) as a continuous predictor. We want to address the research question: “Is there a relationship between perceived fairness and satisfaction and attitudes on wealth redistribution?”</p></li>
<li><p>You will use perceived fairness and satisfaction (<code>fairness_satisfaction</code>) as the outcome and gender (<code>gender</code>) as a categorical predictor. We want to address the research question: “Is there a difference between men and women on perceived fairness and satisfaction?”</p></li>
</ol>
<div class="sourceCode" id="cb21"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">dawtry</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="st">"data/Dawtry-2015.csv"</span><span class="op">)</span></span>
<span></span>
<span><span class="va">dawtry</span> <span class="op">&lt;-</span> <span class="va">dawtry</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>fairness_satisfaction <span class="op">=</span> <span class="op">(</span><span class="va">fairness</span> <span class="op">+</span> <span class="va">satisfaction</span><span class="op">)</span> <span class="op">/</span> <span class="fl">2</span>, <span class="co"># Calculate mean of fairness and satisfaction</span></span>
<span>         <span class="fu"><a href="https://dplyr.tidyverse.org/reference/across.html">across</a></span><span class="op">(</span>.cols <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">redist2</span>, <span class="va">redist4</span><span class="op">)</span>, <span class="op">~</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/case_when.html">case_when</a></span><span class="op">(</span><span class="va">.</span> <span class="op">==</span> <span class="fl">1</span> <span class="op">~</span> <span class="fl">6</span>, <span class="co"># Reverse code two variables</span></span>
<span>                                                         <span class="va">.</span> <span class="op">==</span> <span class="fl">2</span> <span class="op">~</span> <span class="fl">5</span>,</span>
<span>                                                         <span class="va">.</span> <span class="op">==</span> <span class="fl">3</span> <span class="op">~</span> <span class="fl">4</span>,</span>
<span>                                                         <span class="va">.</span> <span class="op">==</span> <span class="fl">4</span> <span class="op">~</span> <span class="fl">3</span>,</span>
<span>                                                         <span class="va">.</span> <span class="op">==</span> <span class="fl">5</span> <span class="op">~</span> <span class="fl">2</span>,</span>
<span>                                                         <span class="va">.</span> <span class="op">==</span> <span class="fl">6</span> <span class="op">~</span> <span class="fl">1</span><span class="op">)</span><span class="op">)</span>,</span>
<span>         redistribution <span class="op">=</span> <span class="op">(</span><span class="va">redist1</span> <span class="op">+</span> <span class="va">redist2</span> <span class="op">+</span> <span class="va">redist3</span> <span class="op">+</span> <span class="va">redist4</span><span class="op">)</span> <span class="op">/</span> <span class="fl">4</span>, <span class="co"># Calculate mean of support for redistribution</span></span>
<span>         gender <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">gender</span>, <span class="co">#Convert gender to a factor</span></span>
<span>                         levels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">2</span><span class="op">)</span>, <span class="co"># original levels as 1 and 2</span></span>
<span>                         labels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Men"</span>, <span class="st">"Women"</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="co"># Create more informative labels</span></span></code></pre></div>
<div class="try">
<p>From here, apply what you learnt in the guided examples above to this new independent task and complete the questions below to check your understanding. Careful in interpreting the fairness and satisfaction item. It is coded a little weird in the original study where higher values mean greater <em>dissatisfaction</em> with the current system of wealth redistribution.</p>
</div>
<div id="predicting-fairness-and-satisfaction-from-redistribution-attitude" class="section level3" number="1.6.1">
<h3>
<span class="header-section-number">1.6.1</span> Predicting fairness and satisfaction from redistribution attitude<a class="anchor" aria-label="anchor" href="#predicting-fairness-and-satisfaction-from-redistribution-attitude"><i class="fas fa-link"></i></a>
</h3>
<ul>
<li><p>Rounding to two decimals, what is the intercept for fairness and satisfaction when redistribution is 0? <input class="webex-solveme nospaces" data-tol="0.001" size="4" data-answer='["8.36"]'></p></li>
<li><p>Rounding to two decimals, the slope for the effect of redistribution on fairness and satisfaction is <input class="webex-solveme nospaces" data-tol="0.001" size="5" data-answer='["-1.23"]'> with a 95% confidence interval spanning from <input class="webex-solveme nospaces" data-tol="0.001" size="5" data-answer='["-1.38"]'> to <input class="webex-solveme nospaces" data-tol="0.001" size="5" data-answer='["-1.09"]'>.</p></li>
<li><p>There is a <select class="webex-select"><option value="blank"></option>
<option value="x">positive</option>
<option value="answer">negative</option>
<option value="x">non-significant</option></select> relationship between fairness and satisfaction and attitudes to wealth redistribution, meaning as attitudes on wealth distribution increase, people are more <select class="webex-select"><option value="blank"></option>
<option value="x">satisfied</option>
<option value="answer">dissatisfied</option></select> with the current system of wealth distribution.</p></li>
<li><p>Rounding to three decimals, adjusted <span class="math inline">\(R^2\)</span> for the model is <input class="webex-solveme nospaces" data-tol="0.001" size="5" data-answer='["0.489",".489"]'>, meaning the predictor explains <input class="webex-solveme nospaces" data-tol="0.001" size="2" data-answer='["49"]'>% of the variance in our outcome.</p></li>
</ul>
</div>
<div id="predicting-fairness-and-satisfaction-from-gender" class="section level3" number="1.6.2">
<h3>
<span class="header-section-number">1.6.2</span> Predicting fairness and satisfaction from gender<a class="anchor" aria-label="anchor" href="#predicting-fairness-and-satisfaction-from-gender"><i class="fas fa-link"></i></a>
</h3>
<ul>
<li><p>Rounding to two decimals, what is the intercept for fairness and satisfaction for men as the reference group? <input class="webex-solveme nospaces" data-tol="0.001" size="4" data-answer='["3.54"]'></p></li>
<li><p>Rounding to two decimals, the slope for the difference between men and women on perceived fairness and satisfaction is <input class="webex-solveme nospaces" data-tol="0.001" size="5" data-answer='["-0.02","-.02"]'> with a 95% confidence interval spanning from <input class="webex-solveme nospaces" data-tol="0.001" size="5" data-answer='["-0.48","-.48"]'> to <input class="webex-solveme nospaces" data-tol="0.001" size="4" data-answer='["0.44",".44"]'>.</p></li>
<li><p>There is a <select class="webex-select"><option value="blank"></option>
<option value="x">positive</option>
<option value="x">negative</option>
<option value="answer">non-significant</option></select> difference between men and women on perceived fairness and satisfaction and attitudes to wealth redistribution.</p></li>
<li><p>Rounding to three decimals, adjusted <span class="math inline">\(R^2\)</span> for the model is <input class="webex-solveme nospaces" data-tol="0.001" size="6" data-answer='["-0.003","-.003"]'>, meaning the predictor explains <input class="webex-solveme nospaces" data-tol="0.001" size="1" data-answer='["0"]'>% of the variance in our outcome.</p></li>
</ul>
</div>
</div>
<div id="further-resources" class="section level2" number="1.7">
<h2>
<span class="header-section-number">1.7</span> Further resources<a class="anchor" aria-label="anchor" href="#further-resources"><i class="fas fa-link"></i></a>
</h2>
<p>Within the School of Psychology and Neuroscience, we have a series of PsyTeachR books. We have written this book to specifically support the statistics and research design course, but you might find other books useful:</p>
<ol style="list-style-type: decimal">
<li><p><a href="https://psyteachr.github.io/quant-fun-v2/index.html" target="_blank">Fundamentals of Quantitative Analysis</a> is a crash course in using R for data wrangling, visualisation, and statistical tests.</p></li>
<li><p><a href="https://psyteachr.github.io/stat-models-v1/" target="_blank">Learning Statistical Models Through Simulation in R</a> covers similar content to this course, but it has slightly longer to walk through different concepts, so you might find it useful as a supplementary source.</p></li>
</ol>
</div>
<div id="C1_solution" class="section level2" number="1.8">
<h2>
<span class="header-section-number">1.8</span> Independent activity solution<a class="anchor" aria-label="anchor" href="#C1_solution"><i class="fas fa-link"></i></a>
</h2>
<div id="predicting-fairness-and-satisfaction-from-redistribution-attitude-1" class="section level3" number="1.8.1">
<h3>
<span class="header-section-number">1.8.1</span> Predicting fairness and satisfaction from redistribution attitude<a class="anchor" aria-label="anchor" href="#predicting-fairness-and-satisfaction-from-redistribution-attitude-1"><i class="fas fa-link"></i></a>
</h3>
<p>First, we can plot the data to check out the relationship and initial patterns.</p>
<div class="sourceCode" id="cb22"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">dawtry</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">fairness_satisfaction</span>, y <span class="op">=</span> <span class="va">redistribution</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_smooth.html">geom_smooth</a></span><span class="op">(</span>method <span class="op">=</span> <span class="st">"lm"</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Fairness and Satisfaction"</span>,</span>
<span>       y <span class="op">=</span> <span class="st">"Support for Redistribution"</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_continuous.html">scale_y_continuous</a></span><span class="op">(</span>breaks <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="fl">6</span><span class="op">)</span>, limits <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>,<span class="fl">6</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_continuous.html">scale_x_continuous</a></span><span class="op">(</span>breaks <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="fl">7</span><span class="op">)</span>, limits <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>,<span class="fl">7</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_minimal</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="01-LM1_files/figure-html/unnamed-chunk-17-1.png" width="100%" style="display: block; margin: auto;"></div>
<p>We can then fit the model using one outcome and one continuous predictor. We get a summary of the model and calculate the confidence intervals for the estimates.</p>
<div class="sourceCode" id="cb23"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">dawtry_continuous</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">fairness_satisfaction</span> <span class="op">~</span> <span class="va">redistribution</span>, data <span class="op">=</span> <span class="va">dawtry</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">dawtry_continuous</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/confint.html">confint</a></span><span class="op">(</span><span class="va">dawtry_continuous</span><span class="op">)</span></span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = fairness_satisfaction ~ redistribution, data = dawtry)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -4.8957 -0.9281 -0.1197  0.9128  6.4226 
## 
## Coefficients:
##                Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)     8.36323    0.29437   28.41   &lt;2e-16 ***
## redistribution -1.23378    0.07224  -17.08   &lt;2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 1.448 on 303 degrees of freedom
## Multiple R-squared:  0.4905, Adjusted R-squared:  0.4888 
## F-statistic: 291.7 on 1 and 303 DF,  p-value: &lt; 2.2e-16
## 
##                    2.5 %    97.5 %
## (Intercept)     7.783963  8.942498
## redistribution -1.375942 -1.091622</code></pre>
</div>
<div id="predicting-fairness-and-satisfaction-from-gender-1" class="section level3" number="1.8.2">
<h3>
<span class="header-section-number">1.8.2</span> Predicting fairness and satisfaction from gender<a class="anchor" aria-label="anchor" href="#predicting-fairness-and-satisfaction-from-gender-1"><i class="fas fa-link"></i></a>
</h3>
<p>First, we can plot the data to check out the relationship and initial patterns.</p>
<div class="sourceCode" id="cb25"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">dawtry</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://tidyr.tidyverse.org/reference/drop_na.html">drop_na</a></span><span class="op">(</span><span class="va">gender</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="co"># Avoid plotting the NAs</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">gender</span>, y <span class="op">=</span> <span class="va">redistribution</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_boxplot.html">geom_boxplot</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Gender"</span>,</span>
<span>       y <span class="op">=</span> <span class="st">"Support for Redistribution"</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_continuous.html">scale_y_continuous</a></span><span class="op">(</span>breaks <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="fl">6</span><span class="op">)</span>, limits <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>,<span class="fl">6</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_minimal</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="01-LM1_files/figure-html/unnamed-chunk-19-1.png" width="100%" style="display: block; margin: auto;"></div>
<p>We can then fit the model using one outcome and one continuous predictor. We get a summary of the model and calculate the confidence intervals for the estimates.</p>
<div class="sourceCode" id="cb26"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">dawtry_gender</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">fairness_satisfaction</span> <span class="op">~</span> <span class="va">gender</span>, data <span class="op">=</span> <span class="va">dawtry</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">dawtry_gender</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/confint.html">confint</a></span><span class="op">(</span><span class="va">dawtry_gender</span><span class="op">)</span></span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = fairness_satisfaction ~ gender, data = dawtry)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -2.5414 -1.5371 -0.5241  1.4586  5.4759 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  3.54140    0.16246  21.798   &lt;2e-16 ***
## genderWomen -0.01726    0.23446  -0.074    0.941    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 2.036 on 300 degrees of freedom
##   (3 observations deleted due to missingness)
## Multiple R-squared:  1.807e-05,  Adjusted R-squared:  -0.003315 
## F-statistic: 0.005421 on 1 and 300 DF,  p-value: 0.9414
## 
##                  2.5 %    97.5 %
## (Intercept)  3.2216926 3.8611099
## genderWomen -0.4786594 0.4441327</code></pre>

</div>
</div>
</div>
<script>

/* update total correct if #webex-total_correct exists */
update_total_correct = function() {
  console.log("webex: update total_correct");

  if (t = document.getElementById("webex-total_correct")) {
    var correct = document.getElementsByClassName("webex-correct").length;
    var solvemes = document.getElementsByClassName("webex-solveme").length;
    var radiogroups = document.getElementsByClassName("webex-radiogroup").length;
    var selects = document.getElementsByClassName("webex-select").length;

    t.innerHTML = correct + " of " + (solvemes + radiogroups + selects) + " correct";
  }
}

/* webex-solution button toggling function */
b_func = function() {
  console.log("webex: toggle hide");

  var cl = this.parentElement.classList;
  if (cl.contains('open')) {
    cl.remove("open");
  } else {
    cl.add("open");
  }
}

/* function for checking solveme answers */
solveme_func = function(e) {
  console.log("webex: check solveme");

  var real_answers = JSON.parse(this.dataset.answer);
  var my_answer = this.value;
  var cl = this.classList;
  if (cl.contains("ignorecase")) {
    my_answer = my_answer.toLowerCase();
  }
  if (cl.contains("nospaces")) {
    my_answer = my_answer.replace(/ /g, "")
  }

  if (my_answer == "") {
    cl.remove("webex-correct");
    cl.remove("webex-incorrect");
  } else if (real_answers.includes(my_answer)) {
    cl.add("webex-correct");
    cl.remove("webex-incorrect");
  } else {
    cl.add("webex-incorrect");
    cl.remove("webex-correct");
  }

  // match numeric answers within a specified tolerance
  if(this.dataset.tol > 0){
    var tol = JSON.parse(this.dataset.tol);
    var matches = real_answers.map(x => Math.abs(x - my_answer) < tol)
    if (matches.reduce((a, b) => a + b, 0) > 0) {
      cl.add("webex-correct");
    } else {
      cl.remove("webex-correct");
    }
  }

  // added regex bit
  if (cl.contains("regex")){
    answer_regex = RegExp(real_answers.join("|"))
    if (answer_regex.test(my_answer)) {
      cl.add("webex-correct");
    }
  }

  update_total_correct();
}

/* function for checking select answers */
select_func = function(e) {
  console.log("webex: check select");

  var cl = this.classList

  /* add style */
  cl.remove("webex-incorrect");
  cl.remove("webex-correct");
  if (this.value == "answer") {
    cl.add("webex-correct");
  } else if (this.value != "blank") {
    cl.add("webex-incorrect");
  }

  update_total_correct();
}

/* function for checking radiogroups answers */
radiogroups_func = function(e) {
  console.log("webex: check radiogroups");

  var checked_button = document.querySelector('input[name=' + this.id + ']:checked');
  var cl = checked_button.parentElement.classList;
  var labels = checked_button.parentElement.parentElement.children;

  /* get rid of styles */
  for (i = 0; i < labels.length; i++) {
    labels[i].classList.remove("webex-incorrect");
    labels[i].classList.remove("webex-correct");
  }

  /* add style */
  if (checked_button.value == "answer") {
    cl.add("webex-correct");
  } else {
    cl.add("webex-incorrect");
  }

  update_total_correct();
}

window.onload = function() {
  console.log("webex onload");
  /* set up solution buttons */
  var buttons = document.getElementsByTagName("button");

  for (var i = 0; i < buttons.length; i++) {
    if (buttons[i].parentElement.classList.contains('webex-solution')) {
      buttons[i].onclick = b_func;
    }
  }

  /* set up webex-solveme inputs */
  var solveme = document.getElementsByClassName("webex-solveme");

  for (var i = 0; i < solveme.length; i++) {
    /* make sure input boxes don't auto-anything */
    solveme[i].setAttribute("autocomplete","off");
    solveme[i].setAttribute("autocorrect", "off");
    solveme[i].setAttribute("autocapitalize", "off");
    solveme[i].setAttribute("spellcheck", "false");
    solveme[i].value = "";

    /* adjust answer for ignorecase or nospaces */
    var cl = solveme[i].classList;
    var real_answer = solveme[i].dataset.answer;
    if (cl.contains("ignorecase")) {
      real_answer = real_answer.toLowerCase();
    }
    if (cl.contains("nospaces")) {
      real_answer = real_answer.replace(/ /g, "");
    }
    solveme[i].dataset.answer = real_answer;

    /* attach checking function */
    solveme[i].onkeyup = solveme_func;
    solveme[i].onchange = solveme_func;

    $(solveme[i]).after(" <span class='webex-icon'></span>");
  }

  /* set up radiogroups */
  var radiogroups = document.getElementsByClassName("webex-radiogroup");
  for (var i = 0; i < radiogroups.length; i++) {
    radiogroups[i].onchange = radiogroups_func;
  }

  /* set up selects */
  var selects = document.getElementsByClassName("webex-select");
  for (var i = 0; i < selects.length; i++) {
    selects[i].onchange = select_func;
    $(selects[i]).after(" <span class='webex-icon'></span>");
  }

  update_total_correct();
}

</script><script>
$( document ).ready(function() {
  var cite = ' ';
  var psyteachr = ' <a href="https://psyteachr.github.io/"><img src="images/logos/psyteachr_logo.png" style="height: 31px; color: white;" alt="psyTeachR: Reproducible Research" /></a>';
  var license = ' <a rel="license" href="https://creativecommons.org/licenses/by-sa/4.0/" target="blank"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png"></a>';

  $("footer div.row div:eq(1) p").html(
    psyteachr + license + cite
  );

  // open rdrr links externally
  $("a[href^='https://rdrr.io']").click(function(){
    window.open(this.href);
    return false;
  });

  // visible second sidebar in mobile
  function move_sidebar() {
    var w = window.innerWidth;
    if (w < 992) {
      $("#toc").appendTo($("#main-nav"));
    } else {
      $("#toc").appendTo($("div.sidebar-chapter"));
    }
  }
  move_sidebar();
  window.onresize = move_sidebar;
});
</script><div class="chapter-nav">
<div class="prev"><a href="index.html">Overview</a></div>
<div class="next"><a href="multiple-linear-regression.html"><span class="header-section-number">2</span> Multiple Linear Regression</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#introduction-to-linear-regression"><span class="header-section-number">1</span> Introduction to Linear Regression</a></li>
<li><a class="nav-link" href="#learning-objectives"><span class="header-section-number">1.1</span> Learning objectives</a></li>
<li>
<a class="nav-link" href="#packages-and-the-data-set"><span class="header-section-number">1.2</span> Packages and the data set</a><ul class="nav navbar-nav"><li><a class="nav-link" href="#exploratory-data-analysis"><span class="header-section-number">1.2.1</span> Exploratory data analysis</a></li></ul>
</li>
<li>
<a class="nav-link" href="#LM_groups"><span class="header-section-number">1.3</span> Simple linear regression for one categorical predictor</a><ul class="nav navbar-nav"><li><a class="nav-link" href="#checking-the-statistical-assumptions"><span class="header-section-number">1.3.1</span> Checking the statistical assumptions</a></li></ul>
</li>
<li>
<a class="nav-link" href="#LM_continuous"><span class="header-section-number">1.4</span> Simple linear regression with one continuous predictor</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#centering-continuous-predictors"><span class="header-section-number">1.4.1</span> Centering continuous predictors</a></li>
<li><a class="nav-link" href="#checking-the-statistical-assumptions-1"><span class="header-section-number">1.4.2</span> Checking the statistical assumptions</a></li>
</ul>
</li>
<li><a class="nav-link" href="#reporting-the-results-of-linear-regression"><span class="header-section-number">1.5</span> Reporting the results of linear regression</a></li>
<li>
<a class="nav-link" href="#independent-activity"><span class="header-section-number">1.6</span> Independent activity</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#predicting-fairness-and-satisfaction-from-redistribution-attitude"><span class="header-section-number">1.6.1</span> Predicting fairness and satisfaction from redistribution attitude</a></li>
<li><a class="nav-link" href="#predicting-fairness-and-satisfaction-from-gender"><span class="header-section-number">1.6.2</span> Predicting fairness and satisfaction from gender</a></li>
</ul>
</li>
<li><a class="nav-link" href="#further-resources"><span class="header-section-number">1.7</span> Further resources</a></li>
<li>
<a class="nav-link" href="#C1_solution"><span class="header-section-number">1.8</span> Independent activity solution</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#predicting-fairness-and-satisfaction-from-redistribution-attitude-1"><span class="header-section-number">1.8.1</span> Predicting fairness and satisfaction from redistribution attitude</a></li>
<li><a class="nav-link" href="#predicting-fairness-and-satisfaction-from-gender-1"><span class="header-section-number">1.8.2</span> Predicting fairness and satisfaction from gender</a></li>
</ul>
</li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
<li><a id="book-source" href="https://github.com/psyteachr/statsresdesign/blob/master/book/01-LM1.Rmd">View source <i class="fab fa-github"></i></a></li>
          <li><a id="book-edit" href="https://github.com/psyteachr/statsresdesign/edit/master/book/01-LM1.Rmd">Edit this page <i class="fab fa-github"></i></a></li>
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>Statistics and Research Design</strong>" was written by James Bartlett. It was last built on 2024-03-18.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script><script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>
</html>
